liip_imagine:
   # valid drivers options include "gd" or "gmagick" or "imagick"
   driver: "gd"

   # define your filter sets under this option
   filter_sets:

       # an example thumbnail transformation definition
       # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
       test:

           # set your image quality defaults
           jpeg_quality:          85
           png_compression_level: 8

           # setup the filter steps to apply for this transformation
           filters:
               # scale and square the image to the given dimensions
               thumbnail:
                   size:          [253, 253]
                   mode:          outbound
                   allow_upscale: true
       users:
           # set your image quality defaults
           jpeg_quality:          85
           png_compression_level: 8

           # setup the filter steps to apply for this transformation
           filters:
               # scale and square the image to the given dimensions
               thumbnail:
                   size:          [125, 125]
                   mode:          outbound
                   allow_upscale: true

