twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        image_upload_path: 'uploads/images/'
        users_image_path: 'uploads/images/user/'




